Factory = Factory or require('rosie').Factory

Factory.define('Me')
  .sequence('id')
  .attr('first_name', 'Richard')
  .attr('last_name', 'Branson')
  .attr('email', 'sir.richard@example.com')
  .attr('charity', 'American National Red Cross')
  .attr('charity_id', 3)
  .attr('flags_count', 0)
  .attr('profile_photo_url', 'http://dummyimage.com/75x75/000/fff.jpg&text=me')
  .attr('stars_count', 200)
  .attr('residence_city', 'Brooklyn')
  .attr('residence_state', 'NY')
  .attr('top_awards_count', 45)
  .attr('top_finish_count', 12)
  .attr('date_of_birth', '8/12/1985')
  .attr('residence_zip_code', '11201')

Factory.define('Brand')
  .sequence('id')
  .attr('name', 'Bexpedia')
  .attr('slug', 'bexpedia')
  .attr('description', 'The dreams of yesterday are the hopes of today and the reality of tomorrow.')
  .attr('header_image_url', 'http://dummyimage.com/300x128/000/fff.jpg&text=header')
  .attr('logo', 'http://dummyimage.com/33x33/333/fff.jpg&text=logo')
  .attr('actions_count', 12)
  .attr('actions_expiring', 3)
  .attr('actions_in_progress', 2)
  .attr('crowd_participants', 1)
  .attr('me', -> Factory.build('Me'))

Factory.define('Charity')
  .sequence('id')
  .attr('name', 'Bacon Trust')
  .attr('description', 'Trust in Bacon')
  .attr('website_url', 'http://www.trustinbacon.com')
  .attr('logo_url', 'http://www.sixdegrees.org/sites/all/themes/sixdegrees/images/logo-six-degrees.png')
  .attr('default', false)
